project:
  type: website
  output-dir: docs
  
website:
  title: " "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - coursework.qmd
    tools:
      - icon: envelope
        href: "pauledargyte@gmail.com"
        target: _blank
    
  page-footer:
    right: "&copy; 2024, Paulė Dargis"

format:
  html:
    head:
      - <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    theme: vapor
    toc: true


editor: source

