project:
  type: website
  output-dir: docs
  
website:
  title: " PAULĖ "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd   # Link to projects.qmd file
        text: Projects       # Text for the link
      - href: coursework.qmd   # Link to coursework.qmd file
        text: Coursework       # Text for the link
    tools:
      - icon: envelope
        href: "pauledargyte@gmail.com"
        target: _blank
    
  page-footer:
    right: "&copy; 2024, Paulė Dargis"

format:
  html:
    head:
      - <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    theme: simplex
    fontsize: 0.95rem
    toc: true
    


editor: source

