# Curriculum Vitae

## Education

### University of California, Los Angeles
- College of Physical Science
- Expected Graduation: June 2024
- Applied Statistics, master’s Student

### California State University, Long Beach
- College of Liberal Arts
- Graduated: May 2022
- Economics, B.A.

## Work Experience

### St. Antony Pharmacy Inc.
- El Segundo, CA
- Administrative Assistant
- Mar 2020 – Current
  - Manage insurance reconciliations, track controlled stock, maintain accounts, process clinical claims, archive prescriptions
  - Manage sensitive data input in over 15 Excel spreadsheets, retrieve and deliver information quarterly
  - Address and resolve patient concerns

### Boeing Co.
- El Segundo, CA
- Intern
- Jun 2017 – Aug 2020
  - Model, 3-D print, and test antennas for satellites
  - Evaluate and analyze data sets related to antenna performance

### The Habit Burger Grill
- El Segundo, CA
- Clerk
- April 2017 – Mar 2020
  - Manage night/closing shifts, inventory management

## Experience

### UCLA Department of Statistics
- Los Angeles, CA
- Researcher
- Sept. 2022 – Present
  - Currently working on the NADAC Dataset Cause of Death and Variable Significance Comparison
  - UFO Sighting and Recession Analysis
  - Significance of Variable Changes for Bike Rentals

### SMC Department of Engineering
- Santa Monica, CA
- Student
- Aug. 2018 – Oct. 2019
  - Introductory physics classes focused on kinematics, magnetism, electricity, and optics with lab

### Northrup Grumman Innovation Challenge
- El Segundo, CA
- ESHS Robotics Team
- Aug. 2015 – Apr. 2017
  - Applied innovative problem-solving skills to design and construct solutions addressing real-world challenges encountered in the aerospace industry
